# Generated by Django 5.0 on 2026-09-09 19:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260909_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Tags',
            },
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Tags',
            },
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tech Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('icon', models.CharField(blank=True, default='⚡', help_text='Emoji or icon identifier', max_length=50)),
                ('category', models.ManyToManyField(blank=True, to='main.skilltag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField(default=django.utils.timezone.now)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Check this box to display this project on the homepage preview.')),
                ('summary', models.CharField(blank=True, help_text='Brief snippet for homepage card. If left blank, description will be truncated.', max_length=300)),
                ('project_tags', models.ManyToManyField(blank=True, to='main.projecttag')),
                ('tech_tags', models.ManyToManyField(blank=True, to='main.techtag')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
